name: Windows manual validation

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - name: Install Ninja
        shell: pwsh
        run: |
          choco install ninja -y
          Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build libultraship
        shell: pwsh
        env:
          VCPKG_ROOT: D:/a/vcpkg
        run: |
          cmake -S . -B build-windows -G Ninja `
            -DCMAKE_MAKE_PROGRAM=ninja `
            -DCMAKE_BUILD_TYPE:STRING=Release `
            -DUSE_AUTO_VCPKG=ON `
            -DCMAKE_VS_PLATFORM_NAME=x64

          cmake --build build-windows --config Release --parallel 10

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: libultraship-windows-x64
          path: build-windows/src/**/*.lib
          if-no-files-found: error
          retention-days: 3
